### ISSUE TITLE
error messages about missing header fields; curl doesn't run

### ISSUE THREAD

**Issue by jrheling** [nordcloud/cognitocurl#15]
Hi! Thanks for a great tool - this looks like a great solution.

I'm having some trouble getting it to work, though. When I invoke it per the docs, like:

`$ cognitocurl --cognitoclient <my_client> --userpool <aws_region-userpool> --run 'curl ...'`

I get:

```
{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=<token>"}
```

and the `curl` command passed to `--run` doesn't seem to actually run.

When I decode the <token> that's output, it's an `id` token rather than an `access` token, FWIW.

Help greatly appreciated.

**Comment by tdi** [comment]
Thanks and sorry for late response. We will look into this immediately.

**Comment by mrichman** [comment]
Similar issue for me:

```
{"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=eyJra...
```

When calling with `--token`, the token returned is an ID token (`"token_use": "id"`).

**Comment by khola** [comment]
Hi, are you sure your API Gateway is using Cognito Authorizer and not IAM Authorizer with SIGv4? 

For Cognito Authorizer both id and access token should work with API Gateway and AppSync according to AWS docs (https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-invoke-api-integrated-with-cognito-user-pool.html)

**Comment by mrichman** [comment]
There are only two options: NONE, and AWS_IAM.

<img width="291" alt="image" src="https://user-images.githubusercontent.com/11228/79159030-58bbcd00-7da5-11ea-93c8-c488d77b416e.png">

**Comment by khola** [comment]
Please refer to https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html

If your API is not properly set up to work with Cognito JWT tokens then this tool is useless.
