### ISSUE TITLE
Installation on mac

### ISSUE THREAD

**Issue by raj2619** [nordcloud/cognitocurl#3]
Hi There,

I'm unable to run "npm -i g" command on mac. I get an undefined error

```
 npm -i g cognitocurl
undefined
```

To overcome this, I've run the following command which installed a whole bunch of packages.

`npm install cognitocurl`

After the running the above command, I see the following in the folder where we installed this -

```
drwxr-xr-x  155 XXXX  wheel   4.8K  6 Mar 11:36 node_modules
-rw-r--r--    1 XXXX  wheel    57K  6 Mar 11:36 package-lock.json
```

When I run the `cognitocurl` command after this, I still get a `-bash: cognitocurl: command not found`
Could you please help fix this problem.

**Comment by khola** [comment]
Hi 

Please use `npm i -g cognitocurl`.

**Comment by raj2619** [comment]
Awesome. Thanks mate. It works.
