### ISSUE TITLE
On successful login, token is output to console and curl command doesn't run

### ISSUE THREAD

**Issue by scrawlon** [nordcloud/cognitocurl#8]
I'm attempting to use the cli command: 
`cognitocurl --cognitoclient <client_id> --userpool <pool_id> --run "curl '<api-gateway-url>'"`

Upon entering correct username and password, the token displays on the command line, and nothing else happens. 

My environment: MacOS 10.14.5, Node 10.16.3, cognitocurl 0.1.6

Let me know if you need any more info. Thanks.

**Comment by khola** [comment]
Yep, you've found a bug ;) 

I've just released 0.1.7 with a bugfix, please update and check if it works for you.

**Comment by scrawlon** [comment]
That fixed it. Thanks.
